[server]
port=9988

[theme]
primaryColor = "#1a73e8"               # Primary color (links, buttons)
backgroundColor = "#f0f0f0"             # Background color for the app
secondaryBackgroundColor = "#f5f5f5"    # Background color for containers
textColor = "#000000"                    # Color of the text
font = "sans serif"                      # Font family

