[nav]
background_color = "white"
padding = "0 200px"  # Add padding to create space on the sides
height = "60px"

[img]
width = "180px"
height = "auto"
padding_right = "14px"

[span]
color = "var(--text-color)"
padding = "14px"

[active]
background_color = "#E4ECFA"
color = "var(--text-color)"
font_weight = "normal"
padding = "14px"
